// Enums
import { color_code_answer_button, answer_option } from '../enums/global_colors';

export const section_questions = {
    section_1 : [
        {   
            question_no: 1,
            question_text: "What was the day of week on 17th June 1998? because there may be some important event should be there so please give your answer accordingly.",
            options:{ a: "What was the day of week on 17th June 1998, Tuesday, Monday Wednesday", b: "Monday", c: "Thursday", d: "What was the day of week on 17th June 1998, Tuesday, Monday Wednesday, week on 17th June 1998, Tuesday, Monday Wednesday" },
            right_answer: "b",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 60,
            visited_not_answer: false, 
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 2,
            question_text: "The below figure shows the two equal forces at right angles acting at a point. The value of force R acting along their bisector and in opposite direction is. the two equal forces at right angles acting at a point. From another point",
            options:{ a: "P/2", b: "2P", c: "P", d: "P/5*2" },
            right_answer: "",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: true,
            descriptive_rigth_answer: "5",
            descriptive_given_answer: "",
            image_url: "https://www.indiabix.com/_files/images/mechanical-engineering/engineering-mechanics/4-22-1.png",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 3,
            question_text: "What is mean by test2?",
            options:{ a: 2, b: 1, c: 5, d: 6 },
            right_answer: "c",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 4,
            question_text: "What was the day of week on 19th June 1998?",
            options:{ a: "Monday", b: "Wednesday", c: "Saturday", d: "Friday" },
            right_answer: "a",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "https://pictures.topspeed.com/IMG/crop/201605/2016_monster_1200_800x0w.jpg",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 5,
            question_text: "Identify the flowers shown in the image?",
            options:{ },
            right_answer: "",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: true,
            descriptive_rigth_answer: "Rose",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 6,
            question_text: "The below figure shows the two equal forces at right angles acting at a point. The value of force R acting along their bisector and in opposite direction is. the two equal forces at right angles acting at a point. From another point.",
            options:[
                {
                    id: "a",
                    option: "The below figure shows the two equal forces at right angles acting at a point. The value of force R acting along their bisector and in opposite direction is. the two equal forces at right angles acting at a point. From another point"
                },
                {
                    id: "b",
                    option: "Test 2"
                },
                {
                    id: "c",
                    option: "The below figure shows the two equal forces at right angles acting at a point. The value of force R acting along their bisector and in opposite direction is. the two equal forces at right angles acting at a point. From another point"
                },
                {
                    id: "d",
                    option: "Test 4"
                }
            ],
            right_answer: "",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: true,
            multiselect_selected_boolean: [false, false, false, false],
            answer_multiselect:[],
            right_answer_multiselect: ["Test 2", "Test 4"],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        }
    ],
    section_2 : [
        {
            question_no: 7,
            question_text: "What is mean by test10? Coz mean by test10.",
            options:{ a: 58, b: 44, c: 3, d: 87 },
            right_answer: "b",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "https://www.1800flowers.com/blog/wp-content/uploads/2019/07/dahlia-flowers-orange-purple-300x199.jpg",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 8,
            question_text: "What is mean by test11? What is mean by test?",
            options:[
                {
                    id: "a",
                    option: "Test 5"
                },
                {
                    id: "b",
                    option: "Test 6"
                },
                {
                    id: "c",
                    option: "Test 7"
                },
                {
                    id: "d",
                    option: "Test 8"
                }
            ],
            right_answer: "",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: true,
            multiselect_selected_boolean: [false, false, false, false],
            answer_multiselect:[],
            right_answer_multiselect: ["Test 5", "Test 8"],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 9,
            question_text: "What was the day of week on 25th June 1900?",
            options:{ a: "Friday", b: "Saturday", c: "Wednesday", d: "Monday"},
            right_answer: "",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: true,
            descriptive_rigth_answer: "wednesday",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 10,
            question_text: "What is mean by test13? Coz mean by test13.",
            options:{ a: 8, b: 4, c: 3, d: 87 },
            right_answer: "c",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 11,
            question_text: "What is mean by test14? What is mean by test14?",
            options:{ a: 8, b: 5, c: 4, d: 5 },
            right_answer: "b",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        }
    ],
    section_3 : [
        {
            question_no: 12,
            question_text: "What is mean by test13? Coz mean by test13.",
            options:{ a: 8, b: 4, c: 3, d: 87 },
            right_answer: "d",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 13,
            question_text: "What is mean by test14? What is mean by test14?",
            options:{ a: "What is mean by test14? What is mean by test14?", b: 5, c: 4, d: 5 },
            right_answer: "b",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 14,
            question_text: "What will the day of week on 25th June 2020?",
            options:{ a: "Friday", b: "Saturday", c: "Wednesday", d: "Monday"},
            right_answer: "",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: true,
            descriptive_rigth_answer: "MoNday",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {
            question_no: 15,
            question_text: "What will the day of week on 25th June 2020?",
            options:{ a: "Friday", b: "Saturday", c: "Wednesday", d: "Monday"},
            right_answer: "b",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: true,
            descriptive_rigth_answer: "friday",
            descriptive_given_answer: "",
            image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS92jGwCKmmqe-ZjIDT-RhpZJ8Mv9pcBQ0WKdId1k2qUqSRdkxh&usqp=CAU",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false,
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        },
        {   
            question_no: 16,
            question_text: "What was the day of week on 17th June 1998?",
            options:{ a: "Wednesday", b: "Monday", c: "Thursday", d: "Friday" },
            right_answer: "b",
            selected_option: "",
            mark_review: false,
            save_mark_review: false,
            save: false,
            multiselect: false,
            multiselect_selected_boolean: [],
            answer_multiselect:[],
            right_answer_multiselect: [],
            descriptive_answer: false,
            descriptive_rigth_answer: "",
            descriptive_given_answer: "",
            image_url: "",
            answered: false,
            time_taken_by_question: 0,
            display_time_of_question: 0,
            visited_not_answer: false, 
            question_pallete_color: color_code_answer_button.not_answered,
            optionButtonColorArr: [answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered, answer_option.option_button_not_answered]
        }
    ]
};
    
